spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      database: test_db
      password: root
      port: 27017
      host: localhost
  application:
    name: i-platform